extensions:
  front-matter:
    enabled: true

plugins:
  md041:
    enabled: true
    front_matter_title: "^\\s*description\\s*[:=]"
  md013:
    line_length: 250
    heading_line_length: 250
    code_block_line_length: 250
